name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - Development

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: checkout repo and submodules
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Login To Registry
      uses: docker/login-action@v2
      with:
        registry: "${{ vars.DOCKER_REGISTRY_URL }}"
        username: "${{ secrets.DOCKER_REGISTRY_USER }}"
        password: "${{ secrets.DOCKER_REGISTRY_PASSWORD }}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build SquadJS Image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: "${{ vars.DOCKER_REGISTRY_URL }}/squadjs:latest"
